# Generated by Django 5.2.2 on 2025-06-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Serveurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('disk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeServeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField()),
                ('email', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_lancement', models.DateField()),
                ('ram_util', models.IntegerField()),
                ('ram_ness', models.IntegerField()),
                ('serveur_lanc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.serveurs')),
            ],
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.applications')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.services')),
            ],
        ),
        migrations.AddField(
            model_name='serveurs',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.typeserveurs'),
        ),
        migrations.AddField(
            model_name='applications',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serveur.utilisateurs'),
        ),
    ]
