# Generated by Django 5.2.2 on 2025-06-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='cpu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='applications',
            name='disk',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='applications',
            name='ram',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='applications',
            name='service',
            field=models.ManyToManyField(through='serveur.Ressources', to='serveur.services'),
        ),
        migrations.AddField(
            model_name='services',
            name='cpu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='services',
            name='disk',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='applications',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
